#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

## usage: adr list
##
## Lists the architecture decision records

adr_dir=$("$adr_bin_dir/_adr_dir")

if [ -d $adr_dir ]
then
   find "$adr_dir" -type d -exec find {} -maxdepth 1 -name '*.md' \; | sort
else
    echo "The $adr_dir directory does not exist"
    exit 1
fi

